### PR TITLE
#3560 Fix action update not creating default views

### PR DESCRIPTION
**Pull request by dythya**
Fixes #

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [x] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by camfindlay** [comment]
@dythya thanks, has this been discussed on ckan dev list? Possible upstream patch? Otherwise happy for you to merge and get into action.

**Comment by dythya** [comment]
There has been no activity on that issue since I did the PR here which was noted. I have just added a comment.

**Comment by camfindlay** [comment]
for future reference see https://github.com/ckan/ckan/issues/3560

**Comment by camfindlay** [comment]
Will merge this, we should look to rebase these changes on the latest patch version of CKAN at some point also.

**Comment by dythya** [comment]
PR#2 is a better fix. I had an unnecessary  call to update the updated_package_dict

**Pull request closed without merging**
